### ISSUE TITLE
Cannot use rsync parameter that have quotes

### ISSUE THREAD

**Issue by barius** [addthis/ssync#3]
e.g. ssync -e "ssh -T -c arcfour -o Compression=no -x" which might boost things up when using 10GBE.

When I do this, ssync tells me that things like "arcfour" does not exist. This might be related to how ssh handles quotes, not really a issue of ssync, of course.

**Comment by tea-dragon** [comment]
Haha, this is a pretty late reply, but your culprit looks like it's probably this:

https://github.com/addthis/ssync/blob/master/ssync#L256

Using the "quiet" option could also blow away your '-e' maybe, but from the "does not exist" type error message and the generalization to quotes, line 256 looks most likely.

**Comment by tea-dragon** [comment]
Here, I even made a PR. If you still care after six months, then you sure as heck earned it. If you've moved on, then let this maybe suboptimally allocated effort serve us as a lesson about neglect.

https://github.com/addthis/ssync/pull/4

**Comment by barius** [comment]
Wow, thanks for the reply :D
Actually I've been using stock ssync in our cluster for a couple of months, and the reason that I wanted to speed up rsync is compensated by the fact that ssync starts 2 rsync's on one node at the same time. One rsync gives about ~60MB/s, so two is somewhat enough to fill the 10GBE's ~117MB/s bandwidth.

**Comment by tea-dragon** [comment]
Then I'll merge that PR and maybe it'll all be great.
